
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mytestdb
    username: mytestdb
    password: mytestdb
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
