version: '3.1'

services:

  db:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: mytestdb
      POSTGRES_USER: mytestdb
      POSTGRES_PASSWORD: mytestdb
    volumes:
      - ./postgres/initdb.d:/docker-entrypoint-initdb.d:ro
